![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

In [ ]:
#Escribe el título del proyecto en Markdown
titulo = "La influencia de las redes sociales y las dating apps en el éxito de las relaciones de pareja"

### TEMA

In [ ]:
# Describe brevemente el tema del proyecto en Markdown
tema = "El objetivo es averiguar el impacto que tienen las aplicaciones de citas y las redes sociales en general a la hora de no solamente encontrar pareja, sino su éxito a largo plazo"

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Puede que tengas más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

In [ ]:
# Escribe tu hipótesis principal en Markdown
hipotesis_1 = "El dating online no favorece las relaciones personales a largo plazo"

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [2]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_1 = pd.read_csv('./data/DatingAppReviewsDataset.csv')
fuente_1 = "kaggle"
df_2 = pd.read_csv('./data/Tinder Millennial Match Rate Dataset.csv')
fuente_2 = "kaggle"
df_3 = pd.read_csv('./data/Week 30 - United States Marriage Status 2005 to 2017.csv')
fuente_3 = "kaggle"
df_4 = pd.read_csv('./data/divorce_data.csv')
fuente_4 = "kaggle"

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [3]:
# Primer dataset --> Dating Review
df_1.head()

,Unnamed: 0,Name,Review,Rating,#ThumbsUp,Date&Time,App
0,0,linah sibanda,On this app i cant find a partner,5,0,18-02-2022 01:19,Tinder
1,1,Norman Johnson,Tinder would be so much better if we could spe...,3,0,18-02-2022 01:16,Tinder
2,2,David Hume,Still doesn't correctly notify matches or mess...,1,0,18-02-2022 01:11,Tinder
3,3,Last 1 Standing,"Got banned because I updated my bio to say ""I ...",2,0,18-02-2022 01:11,Tinder
4,4,Arthur Magamedov,Love it!,5,0,18-02-2022 01:06,Tinder

In [10]:
df_1

,Name,Review,Rating,#ThumbsUp,Date&Time,App
0,linah sibanda,On this app i cant find a partner,5,0,18-02-2022 01:19,Tinder
1,Norman Johnson,Tinder would be so much better if we could spe...,3,0,18-02-2022 01:16,Tinder
2,David Hume,Still doesn't correctly notify matches or mess...,1,0,18-02-2022 01:11,Tinder
3,Last 1 Standing,"Got banned because I updated my bio to say ""I ...",2,0,18-02-2022 01:11,Tinder
4,Arthur Magamedov,Love it!,5,0,18-02-2022 01:06,Tinder
...,...,...,...,...,...,...
681989,A Google user,Useless - I'm in the UK and it tells me i'm ov...,2,5,12-07-2017 01:44,Hinge
681990,Brian Shook,I can't get past the initial set up. It won't...,1,11,12-07-2017 01:36,Hinge
681991,A Google user,This is incredible! A quality dating app for A...,5,1,12-07-2017 01:32,Hinge
681992,A Google user,"""Over Water"" ... Can't choose location.",2,8,12-07-2017 01:28,Hinge
681993,Dylan Fick,"My entire town counts as ""over water"" and I ca...",2,15,12-07-2017 01:24,Hinge

In [15]:
rating_1 = df_1[df_1['Rating']==1]
rating_2 = df_1[df_1['Rating']==2]
rating_3 = df_1[df_1['Rating']==3]
rating_4 = df_1[df_1['Rating']==4]
rating_5 = df_1[df_1['Rating']==5]

In [14]:
len(rating_1)/len(df_1)

0.36945926210494523

In [16]:
len(rating_2)/len(df_1)

0.07662090868834623

In [17]:
len(rating_3)/len(df_1)

0.08351686378472538

In [18]:
len(rating_4)/len(df_1)

0.12807590682615977

In [19]:
len(rating_5)/len(df_1)

0.3423255923072637

In [22]:
rating_1_Tinder = df_1[(df_1['Rating'] == 1) & (df_1['App'] == 'Tinder')]
rating_2_Tinder = df_1[(df_1['Rating'] == 2) & (df_1['App'] == 'Tinder')]
rating_3_Tinder = df_1[(df_1['Rating'] == 3) & (df_1['App'] == 'Tinder')]
rating_4_Tinder = df_1[(df_1['Rating'] == 4) & (df_1['App'] == 'Tinder')]
rating_5_Tinder = df_1[(df_1['Rating'] == 5) & (df_1['App'] == 'Tinder')]

In [32]:
tinder = df_1[df_1['App']=='Tinder'].dropna()

In [33]:
len(rating_1_Tinder)/len(tinder)

0.37247375946477496

In [36]:
len(rating_2_Tinder)/len(tinder)

0.07248537326959067

In [37]:
len(rating_3_Tinder)/len(tinder)

0.08154033322100308

In [38]:
len(rating_4_Tinder)/len(tinder)

0.12402210811500332

In [39]:
len(rating_5_Tinder)/len(tinder)

0.3521020034765258

### Los usuarios o odian o aman las apps de citas. Muy dispar la valoracion. Tiende a ser la misma en todas las apps

In [49]:
# Milennial Rate Match
df_2.head(20)

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes
1,292883,Mobile,Mobile respondents,No,1969,0.511,No
2,292885,Mobile,Mobile respondents,I don't use Tinder,1090,0.283,Yes
3,292887,Web,Web-based respondents,Yes,0,0.000,No
4,292889,Web,Web-based respondents,No,0,0.000,No
5,292891,Web,Web-based respondents,I don't use Tinder,0,0.000,No
6,292893,Gender,Male respondents,Yes,472,0.213,Yes
7,292895,Gender,Male respondents,No,1172,0.528,No
8,292897,Gender,Male respondents,I don't use Tinder,574,0.259,No
9,292899,Gender,Female respondents,Yes,325,0.198,No
10,292901,Gender,Female respondents,No,797,0.487,Yes
11,292903,Gender,Female respondents,I don't use Tinder,516,0.315,No
12,292905,University,Chapman University,Yes,13,0.206,No
13,292907,University,Chapman University,No,31,0.492,No
14,292909,University,Chapman University,I don't use Tinder,19,0.302,Yes
15,292911,University,Cornell University,Yes,47,0.244,No
16,292913,University,Cornell University,No,95,0.492,Yes
17,292915,University,Cornell University,I don't use Tinder,51,0.264,No
18,292917,University,Duke University,Yes,0,0.000,No
19,292919,University,Duke University,No,2,0.667,No

In [43]:
len(df_2)

453

In [82]:
total = df_2[df_2['Segment Type']=='Mobile']
male = df_2[df_2['Segment Description']=='Male respondents']
female = df_2[df_2['Segment Description']=='Female respondents']
university = df_2[df_2['Segment Type']=='University']

In [83]:
total

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
0,292881,Mobile,Mobile respondents,Yes,797,0.207,Yes
1,292883,Mobile,Mobile respondents,No,1969,0.511,No
2,292885,Mobile,Mobile respondents,I don't use Tinder,1090,0.283,Yes

In [84]:
total.Count.sum()

3856

In [56]:
male

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
6,292893,Gender,Male respondents,Yes,472,0.213,Yes
7,292895,Gender,Male respondents,No,1172,0.528,No
8,292897,Gender,Male respondents,I don't use Tinder,574,0.259,No

In [78]:
male.Count.sum()

2218

In [57]:
female

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
9,292899,Gender,Female respondents,Yes,325,0.198,No
10,292901,Gender,Female respondents,No,797,0.487,Yes
11,292903,Gender,Female respondents,I don't use Tinder,516,0.315,No

In [85]:
female.Count.sum()

1638

In [87]:
(female.Count.sum() + male.Count.sum()) == total.Count.sum()

True

In [58]:
university

,ID,Segment Type,Segment Description,Answer,Count,Percentage,It became a Relationship
12,292905,University,Chapman University,Yes,13,0.206,No
13,292907,University,Chapman University,No,31,0.492,No
14,292909,University,Chapman University,I don't use Tinder,19,0.302,Yes
15,292911,University,Cornell University,Yes,47,0.244,No
16,292913,University,Cornell University,No,95,0.492,Yes
...,...,...,...,...,...,...,...
448,293777,University,Boston College,No,4,0.800,Yes
449,293779,University,Boston College,I don't use Tinder,1,0.200,No
450,293781,University,Boston University,Yes,2,0.333,Yes
451,293783,University,Boston University,No,3,0.500,No
452,293785,University,Boston University,I don't use Tinder,1,0.167,No

In [69]:
university.Count.sum()

2423

In [72]:
university_yes = university[university['Answer'] == 'Yes']

In [75]:
university_yes.Count.sum()

534

In [76]:
university_yes.Count.sum()/university.Count.sum()

0.2203879488237722

### SOLO EL 20% DE LOS MILENNIALS OBTIENEN PAREJA POR TINDER. Los hombres la usan mas, pero obtienen casi el mismo porcentaje que las mujeres

In [90]:
# Siguiente dataset...
df_3.head(50)

,index,Year,Gender,Age Group,Metric,Estimated Percent,Estimated Population
0,0,2008,Male,15 to 19 years,Total,1.000,11241214
1,1,2008,Male,20 to 34 years,Total,1.000,31342886
2,2,2008,Male,35 to 44 years,Total,1.000,21426309
3,3,2008,Male,45 to 54 years,Total,1.000,21889603
4,4,2008,Male,55 to 64 years,Total,1.000,16251184
5,5,2008,Male,65 years and over,Total,1.000,16421811
6,6,2008,Female,15 to 19 years,Total,1.000,10671352
7,7,2008,Female,20 to 34 years,Total,1.000,29987383
8,8,2008,Female,35 to 44 years,Total,1.000,21318283
9,9,2008,Female,45 to 54 years,Total,1.000,22546049
10,10,2008,Female,55 to 64 years,Total,1.000,17466891
11,11,2008,Female,65 years and over,Total,1.000,22390442
12,12,2008,Male,15 to 19 years,Married,0.008,89930
13,13,2008,Male,20 to 34 years,Married,0.319,9998381
14,14,2008,Male,35 to 44 years,Married,0.630,13498575
15,15,2008,Male,45 to 54 years,Married,0.658,14403359
16,16,2008,Male,55 to 64 years,Married,0.718,11668350
17,17,2008,Male,65 years and over,Married,0.713,11708751
18,18,2008,Female,15 to 19 years,Married,0.017,181413
19,19,2008,Female,20 to 34 years,Married,0.391,11725067
20,20,2008,Female,35 to 44 years,Married,0.633,13494473
21,21,2008,Female,45 to 54 years,Married,0.633,14271649
22,22,2008,Female,55 to 64 years,Married,0.617,10777072
23,23,2008,Female,65 years and over,Married,0.404,9045739
24,24,2008,Male,15 to 19 years,Widowed,0.000,0
25,25,2008,Male,20 to 34 years,Widowed,0.001,31343
26,26,2008,Male,35 to 44 years,Widowed,0.004,85705
27,27,2008,Male,45 to 54 years,Widowed,0.010,218896
28,28,2008,Male,55 to 64 years,Widowed,0.024,390028
29,29,2008,Male,65 years and over,Widowed,0.136,2233366
30,30,2008,Female,15 to 19 years,Widowed,0.000,0
31,31,2008,Female,20 to 34 years,Widowed,0.003,89962
32,32,2008,Female,35 to 44 years,Widowed,0.011,234501
33,33,2008,Female,45 to 54 years,Widowed,0.032,721474
34,34,2008,Female,55 to 64 years,Widowed,0.088,1537086
35,35,2008,Female,65 years and over,Widowed,0.426,9538328
36,36,2008,Male,15 to 19 years,Divorced,0.000,0
37,37,2008,Male,20 to 34 years,Divorced,0.037,1159687
38,38,2008,Male,35 to 44 years,Divorced,0.116,2485452
39,39,2008,Male,45 to 54 years,Divorced,0.157,3436668
40,40,2008,Male,55 to 64 years,Divorced,0.154,2502682
41,41,2008,Male,65 years and over,Divorced,0.093,1527228
42,42,2008,Female,15 to 19 years,Divorced,0.001,10671
43,43,2008,Female,20 to 34 years,Divorced,0.053,1589331
44,44,2008,Female,35 to 44 years,Divorced,0.143,3048514
45,45,2008,Female,45 to 54 years,Divorced,0.186,4193565
46,46,2008,Female,55 to 64 years,Divorced,0.196,3423511
47,47,2008,Female,65 years and over,Divorced,0.113,2530120
48,48,2008,Male,15 to 19 years,Separated,0.001,11241
49,49,2008,Male,20 to 34 years,Separated,0.014,438800

In [9]:
# Siguiente dataset...
df_4.head()

  Q1;Q2;Q3;Q4;Q5;Q6;Q7;Q8;Q9;Q10;Q11;Q12;Q13;Q14;Q15;Q16;Q17;Q18;Q19;Q20;Q21;Q22;Q23;Q24;Q25;Q26;Q27;Q28;Q29;Q30;Q31;Q32;Q33;Q34;Q35;Q36;Q37;Q38;Q39;Q40;Q41;Q42;Q43;Q44;Q45;Q46;Q47;Q48;Q49;Q50;Q51;Q52;Q53;Q54;Divorce
0  2;2;4;1;0;0;0;0;0;0;1;0;1;1;0;1;0;0;0;1;0;0;0;...
1  4;4;4;4;4;0;0;4;4;4;4;3;4;0;4;4;4;4;3;2;1;1;0;...
2  2;2;2;2;1;3;2;1;1;2;3;4;2;3;3;3;3;3;3;2;1;0;1;...
3  3;2;3;2;3;3;3;3;3;3;4;3;3;4;3;3;3;3;3;4;1;1;1;...
4  2;2;1;1;1;1;0;0;0;0;0;1;0;1;1;1;1;1;2;1;1;0;0;...